### PR TITLE
new is_container function

### PR DESCRIPTION
**Pull request by ericfrederich**
Hey, this is pretty useful.  I never use is_scalar but the effective inverse is_collection.

### CODE REVIEW

**Comment by ericfrederich** [comment]
Any chance of getting this merged?

**Comment by mahmoud** [comment]
You know, I was waiting for a real application to come along use it myself and feel it out, as I like to do with most contributed boltons, but this is simple enough, so sure why not. :+1:

**Comment by ericfrederich** [comment]
There wasn't any real discussion about this.  I was wondering if is_container is a good name or if it should be is_collection.  I'd be okay with either.

**Comment by mahmoud** [comment]
Hmm, is_collection is pretty good. I'll make that switch.

**Comment by ericfrederich** [comment]
Thanks.
I use `is_collection` quite often when recursing over data structures which aren't strictly defined or of variable depth.  I was doing it today in fact and came to peek of this had been merged.  `not is_scalar` would work too but I think having both `is_scalar` and `is_collection` are useful since they both have meaningful names.

Please don't accept any merge requests for `uncallable` until something that isn't callable has a better name ;-)

**Comment by mahmoud** [comment]
That sounds like sound advice to me :)

**Pull request merged**
