### PR TITLE
Rewrite ANSI stripping code with a regex, add tests.

### PR DESCRIPTION
**Pull request by kdeldycke**
This PR:
* Address #257 by providing more robust ANSI stripping
* Adds supports for `unicode`, `str`, `bytes` and `bytearray` content as input
* Allow the return of the same type as the input
* Add extensive uniit-tests with `unicode`, `str`, `bytes` and `bytearray` types
* Add lots of unit-tests of mangled unicode/ANSI/ASCII strings

### CODE REVIEW

**Comment by kdeldycke** [comment]
It was hard, but I finally found a way to handle all the edge-cases related to types on both Python 2 & 3.

This PR is ready to be squashed and merged! :)

**Comment by mahmoud** [comment]
Big +1 to this! Looking forward to trying it out when I update my CLIs to the upcoming release :) Thanks!

**Comment by kdeldycke** [comment]
Thanks @mahmoud for the merge! Happy to contribute! boltons is one of the hidden gem of Python's ecosystem. 👍

**Comment by kdeldycke** [comment]
Is there any plan to release boltons soon?

**Comment by mahmoud** [comment]
Good news, 20.2.0 released last night! Enjoy! :)

**Pull request merged**
