### PR TITLE
funcutils.wraps: Async coroutine support

### PR DESCRIPTION
**Pull request by mahmoud**
Here's my initial approach at fixing #194 for Py3.5+. Care to take a look @hynek?

### CODE REVIEW

**Comment by hynek** [comment]
There is something not quite right.

```python
def yolo():
    def make_time_decorator(wrapped):
        @wraps(wrapped)
        async def decorator(*args, **kw):
            return (await wrapped(*args, **kw))
        return decorator

    return make_time_decorator


@yolo()
async def foo(x):
    await asyncio.sleep(x)


asyncio.run(foo(5))
```

works with the old version but in the new one, `decorator` is never awaited.

**Comment by mahmoud** [comment]
Ah, I had a suspicion I was forgetting something. Fix pushed.

**Comment by hynek** [comment]
Can’t test rn but I’d suggest to sleep less and use perf_counter or even perf_counter_ns (since it’s 3.7 anyway) to avoid a flaky slow test.

**Comment by mahmoud** [comment]
Hmm, I haven't used it before, but I think perf_counter mostly gives us more resolution, but wouldn't really get rid of exposure to travis pauses.

Anyways, waiting 0.3 seconds won't really break the bank, it's still faster than the gc tests.

I'm fairly confident it's correct now, as I've just checked decorator.py and I landed on a very similar approach to what apparently works over there. :)

**Comment by hynek** [comment]
More importantly it’s monotonic.

**Comment by mahmoud** [comment]
haha, now that's a timely point I can get behind! fixed :)

**Comment by mahmoud** [comment]
prepping for a release, you can try this out in 19.0 ;)

**Pull request merged**
