### PR TITLE
Add badges

### PR DESCRIPTION
**Pull request by kdeldycke**
I suggest to fancy up boltons' readme with badges! :)

### CODE REVIEW

**Comment by kdeldycke** [comment]
Just realized the readme is in Markdown, nor RST... :(

**Comment by kdeldycke** [comment]
Feel free to pick up working badges and close this PR then.

**Comment by mahmoud** [comment]
Hey Kevin, great suggestion! I've added some badges, let me know what you think! In the meantime, I'm gonna close this RST PR :)

**Comment by kdeldycke** [comment]
These badges looks nice on your readme! 💅

**Pull request closed without merging**
