### PR TITLE
added sockutils with BufferedSocket and NetstringSocket

### PR DESCRIPTION
**Pull request by doublereedkurt**
in the interests of not letting the perfect be the enemy of the good, I'm going to go ahead and put out this pull request even though docs are still incomplete, and test coverage is not quite 100%

### CODE REVIEW

**Comment by mahmoud** [comment]
Yes, buffered sockets are definitely something I could see in the standard library. Right now this isn't passing tests on Python 3, but I think I can fix that. I'll manually merge and fix it locally.

**Comment by doublereedkurt** [comment]
Oh right it uses str.join in a bunch of places.... That isn't going to fly
in Python 3

**Comment by mahmoud** [comment]
Haha, you can say that again. Lots of stuff needed tweaking, but it now runs under Python 2.6, 2.7, 3.4, and PyPy. I'll be doing a lot more review, commenting, and documentation before it ends up advertised in the main docs. ;)

**Comment by doublereedkurt** [comment]
Very nice :-)

**Pull request merged**
