### PR TITLE
Improved the build matrix

### PR DESCRIPTION
**Pull request by thedrow**
Added caching and python 3.5 to the build matrix.

### CODE REVIEW

**Comment by mahmoud** [comment]
Hey! Thanks for the PR! 

The results are interesting. As @hynek mentioned, 3.5 appears superborked! A new version of py.test might add the proper ast handling?

Is there any reason to cache? Boltons has few-to-no deps and build times were never the issue. An unnecessary cache is often the cause of a future bug.

The `sudo: false` is also interesting, what's the rationale there? 

Thanks again!

**Comment by hynek** [comment]
`sudo: false` gives you the new (faster) Docker-based infra.  Works only if you don’t need root privileges though.

**Comment by thedrow** [comment]
I can remove the cache if you don't want it. It does save you the trouble of downloading tox & pytest.

**Comment by mahmoud** [comment]
@hynek: Good to know!

@thedrow Allll green, nice. I'll give the cached version a whirl and see how it feels. If the productivity is worth it, it might stick around. Thanks again!

**Comment by thedrow** [comment]
No problem.

**Pull request merged**
