### PR TITLE
poolutils: ThreadPool implementation

### PR DESCRIPTION
**Pull request by srirams6**
Added a poolutils file with ThreadPool.

### CODE REVIEW

**Comment by harvimt** [comment]
How is this more useful than `concurrent.futures.ThreadPoolExecutor`?

**Comment by srirams6** [comment]
Python 2 support?

**Comment by harvimt** [comment]
There's a backport that supports 2.6+.

**Comment by srirams6** [comment]
Yes, so why not add the functionality to boltons?

**Comment by srirams6** [comment]
Bump

**Comment by mahmoud** [comment]
Hey Sriram, sorry it took so long to get back on this. My basic stance on primitives of this level of complexity is that without demonstrating an equivalent level of production-hardenedness, I would find it very difficult to accept such an implementation into boltons. Especially given the following paragraph in [the architecture statement](http://boltons.readthedocs.org/en/latest/architecture.html#design-of-a-bolton): 

> Finally, boltons should be substantial implementations of commonly trivialized stumbling blocks and not the other way around. The larger the problem solved, the less likely the functionality is suitable for inclusion in boltons; boltons are fundamental and self-contained, not sweeping and architecture-defining.

Unfortunately I just don't have the resources or projects right now to take this threadpools out for the requisite spins and rest assured that I've not merged a trivialized version of something I know to be a substantial part of programming.

Finally, Python has a built-in threadpool, in multiprocessing.dummy that can be made to work in a pinch. I've actually used it, and it can certainly be better, but that'll have to wait for another time. Sorry again and thank you for taking the time and creating the contribution all the same.

**Comment by srirams6** [comment]
Yeah. I realized that and closed it. :)

**Comment by mahmoud** [comment]
Cool, it's always bittersweet to not merge, but I'm still glad to have had the privilege to read the code and think on the problem. Thanks again!

**Pull request closed without merging**
