### PR TITLE
suport lists as key for bucketize

### PR DESCRIPTION
**Pull request by matiasmorant**
I was trying to do this and I naturally reached for `bucketize`, but then found it doesn't support lists

### CODE REVIEW

**Comment by mahmoud** [comment]
Interesting idea. I'm not against it, but I'm curious what happens if a value doesn't map to any of the specified buckets?

**Comment by matiasmorant** [comment]
@mahmoud I don't understand the question. You have to specify the bucket for each value, so all values will map to a bucket (`src` and `key` are the same length)

**Comment by kurtbrose** [comment]
huh, I guess you could achieve the same with:

```python
keys = [0, 1, 0]
bucketize('abc', lambda v: keys.pop())
{0: ['a', 'c'], 1: ['b']}
```

although that assumes the key function will be called once per value and in-order
(which is not a terrible assumption for a function which is meant to work with any iterable)

https://pypi.org/project/relativity/ could be helpful

```python
M2M(zip([0, 1, 0], 'abc'))
```

then you'd have, effectively, a dict-of-frozenset rather than dict-of-list

**Comment by matiasmorant** [comment]
Sure, I could also do:
```
bucketize(zip(keys, values), key=lambda x: x[0], value_transform=lambda x: x[1]) 
```
but the point was to make it straightforward:
```
bucketize(values, keys) 
```

**Comment by mahmoud** [comment]
Ah, got it. Let's raise a ValueError if the lengths of the lists aren't equal in that case.

FWIW I usually do a `zip` with an `dictutils.OMD().to_dict()`, but this is definitely more efficient if you don't need the rest of the OMD methods :)

**Comment by matiasmorant** [comment]
@mahmoud  added the ValueError

**Comment by mahmoud** [comment]
Looks good, thanks!

**Pull request merged**
